import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card } from "../components/Cards";
import { Navbar } from "../components/Navbar";
import { SearchBar } from "../components/SearchBar";

const Home: NextPage = () => {
  function onSearch(value: string) {
    console.log(value);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-br from-purple-900 to-blue-700">
        <Navbar />
        <div className="h-screen flex items-center justify-center">
          <SearchBar onSearch={onSearch} />
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
